# Series01-python: ECG signal analysis

## Goal
Display the ECG signal of leads I, II and III in standard units
(millivolts vs seconds).

## Steps
1. Load the raw data from `data/ECGu.txt`
2. Check the data is loaded correctly (values, shape)
3. Rescale the amplitudes to mV using the A/D gain
4. Build the time axis from the sampling frequency
5. Plot the ECG signal
6. Check the plot against what is expected of a normal ECG

In [ ]:
# CELL 1: imports
# numpy to manipulate the ECG data, matplotlib to plot it
import numpy as np
import matplotlib.pyplot as plt

[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 ...
 [  -4.  -83.   21.]
 [  -9.  -88.   31.]
 [ -16.  -96.   33.]]
(6500, 3)
